### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by PrinceAbsolution** [userofbricks/Expanded-Combat#36]
Hello, this mod is crashing whenever I try to put in any ingredient to upgrade my shields.

The error log gives this report: The game crashed whilst container click

Error: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "com.userofbricks.expanded_combat.api.material.Material.getConfig().crafting.craftingItem" is null

I am also having a problem with curios not accepting the gauntlets or quivers.

**Comment by PrinceAbsolution** [comment]
Also the enderite bow is titled enderite gauntlets

**Comment by userofbricks** [comment]
ah ok these should be somewhat simple to fix. the shield issue is cause of a config bug, the gauntlets and quivers puzzle me as to how as I have been fighting a bug that stops the item tag that enables them from being inputed into the slots, but it is a simple but anoying fix. and as for the nederite in the 3.0.0 update of EC I axidentaly had my automatic item generation lableing bows as gauntlets if they don't have a half counterpart, again a simple fix that just requires a rerun of some data generation for enderite.

**Comment by userofbricks** [comment]
the shield issue has been fixed.
what mod are you experiencing the gauntlets and quivers are not able to go into the curios slots. cause the base mod is able to.

**Comment by PrinceAbsolution** [comment]
Sorry for the late response, the only mods I have that I think could be interfering is the aether and supplementaries.

**Comment by PrinceAbsolution** [comment]
The shields are fully working now but curios is still not working with the mod.

**Comment by PrinceAbsolution** [comment]
I check the mod on its own and it is working, so there is some incompatibility. I'm going to try to narrow it down and then I will report back.

**Comment by PrinceAbsolution** [comment]
I cant seem to find the issue. i tried to uninstall curios on my modpack and it didn't go away so i think there might be something up with that that is influencing the mod.

**Comment by PrinceAbsolution** [comment]
I have found the culprit! It is the enderite plugin fro EC that is causing the curios issue.
